language: python
python:
#  - "2.7"
#  - "3.3" # failed due to setuptool version 
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch
#  - "nightly"
    # PyPy versions
#  - "pypy2.7"
#  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
   pytest --cov=pyod/

after_success:
  - coveralls